FROM n8nio/n8n:latest

USER root

# Install Python and pip
RUN apk update && \
    apk add --no-cache python3 py3-pip

# Switch back to node user
USER node

# Add virtual environment to PATH in .bashrc for node user
RUN echo 'export PATH="/opt/venv/bin:$PATH"' >> ~/.bashrc